### ISSUE TITLE
Validation and Test Data Missing.

### ISSUE THREAD

**Issue by Vaishnvi** [Twizwei/bddoia_project#1]
Hi @Twizwei ,

Thanks for sharing this repo :)

I have downloaded lastframe.zip and BDD-OIA.zip as told for data. But I am not finding image data for val and test in there.

As stated in paper, model is trained on 16k images , I found that train image data in lastframe.zip but I can't find 2,270 val images and test set of 4,572 images in those folders. Can you please let me know where could I download them from for evaluation further?

Thanks and regards,
Vaishnavi Khindkar

**Comment by Twizwei** [comment]
Hi Vaishnvi, I put all images in 'data/', where you can find train, val and test
