### ISSUE TITLE
Freezing FasterRCNN option is set to false by default in code and isn't updated by command line arguments

### ISSUE THREAD

**Issue by Vaishnvi** [Twizwei/bddoia_project#2]
Hi @Twizwei ,

Freezeing FasterRCNN option is set to false in code and also it's not set to true via arguments. But in paper it's mentioned that faster rcnn is freezed while training. I have changed it's default value to True as of now and have started training again. 

Do I need to make any other change to replicate the results?

Thanks,
Vaishnavi Khindkar

**Comment by Twizwei** [comment]
Yes, you are correct. This might be a mistake when I was re-writing the code. I'll update my code. Thank you!
